openapi: 3.0.0
info:
  title: Simple API
  version: 1.0.0
servers:
  - url: "/api"
paths:
  /users:
    get:
      summary: Retrieve a list of users
      operationId: service_api_impl.list_users
      responses:
        '200':
          description: A list of user objects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
  /users/{id}:
    get:
      summary: Retrieve a user by ID
      operationId: service_api_impl.get_by_id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A user object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string

